genesys: fix gcc-4.8 compile
Fixes:

  genesys/utilities.h:229:23: error: invalid initialization of non-const reference of type 'std::basic_ios<char>&' from an rvalue of type '<brace-enclosed initializer list>'
           stream_{stream}
                         ^
  genesys/image_pipeline.cpp:715:19: error: invalid initialization of non-const reference of type 'genesys::ImagePipelineNode&' from an rvalue of type '<brace-enclosed initializer list>'
       source_{source}
                     ^

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
(cherry picked from commit 1db13a713f281c66d3eaebab06a33d735ea9c20e)