kodakaio:: Remove Unicode LRO (U+202D) character from comments
GCC 13 error message:

kodakaio.c: In function 'k_init_parametersta':
kodakaio.c:1830:67: error: unpaired UTF-8 bidirectional control character detected [-Werror=bidi-chars=]
 1830 |          * The default color depth is stored in mode_params.depth:<U+202D>
      |                                                                   ~~~~~~~~^
      |                                                                   |       |
      |                                                                   |       end of bidirectional context
      |                                                                   U+202D (LEFT-TO-RIGHT OVERRIDE)

Fixes: 06fae3526 ("kodakaio params.depth corrected for lineart, color mode made the default.")