CI: Add -Wunused-but-set-variable for Fedora clang
clang 17 warnings that need to be fixed:

hp-option.c:3812:10: error: variable 'errcount' set but not used [-Werror,-Wunused-but-set-variable]
 3812 |   int i, errcount = 0;
      |          ^

In file included from hp3900.c:59:
./hp3900_sane.c:1755:12: error: variable 'nline' set but not used [-Werror,-Wunused-but-set-variable]
 1755 |   SANE_Int nline = 0;
      |            ^

lexmark_low.c:2500:7: error: variable 'blackLineCount' set but not used [-Werror,-Wunused-but-set-variable]
 2500 |   int blackLineCount = 0;
      |       ^

In file included from plustek_pp.c:124:
./plustek-pp_io.c:425:8: error: variable 'dwTime' set but not used [-Werror,-Wunused-but-set-variable]
  425 |         ULong dwTime = 1;
      |               ^

genesys/genesys.cpp:843:19: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
  843 |     for (unsigned i = 0;; ++i) {
      |                   ^

After fixing them this commit could be reversed.